name: Test Project

on:
  pull_request:
    branches:
      - "dev"

jobs:
  CI:
    name: Tests pipeline
    runs-on: macos-latest

    steps:
      - name: Install brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        
      - name: Install xcodegen
        run: brew install xcodegen
        
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Selecting Xcode Version
        run: |
          sudo xcode-select -switch /Applications/Xcode_14.3.1.app

      - name: Generating project
        run: xcodegen

      - name: Build project
        run: |
          xcodebuild clean -project MxNetworking.xcodeproj -scheme MxNetworkingDemo

      - name: Test project
        run: |
          xcodebuild test -project MxNetworking.xcodeproj -scheme MxNetworkingDemo -destination 'platform=iOS Simulator,OS=16.4,name=iPhone 14'
